CREATE TABLE regional (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    external_id INT NOT NULL,
    nome VARCHAR(200) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
